import {
    setDefaultTimeout,
    initialized,
    resetTheme,
    ready,
    waitWebFont,
    isWebFontLoaded,
    isCompact,
    isDark,
    isGeneric,
    isMaterial,
    isFluent,
    isMaterialBased,
    detachCssClasses,
    attachCssClasses,
    current,
    waitForThemeLoad,
    isPendingThemeLoaded,
} from '../__internal/ui/m_themes';

export default {
    setDefaultTimeout,
    initialized,
    resetTheme,
    ready,
    waitWebFont,
    isWebFontLoaded,
    isCompact,
    isDark,
    isGeneric,
    isMaterial,
    isFluent,
    isMaterialBased,
    detachCssClasses,
    attachCssClasses,
    current,
    waitForThemeLoad,
    isPendingThemeLoaded,
};
